version: 2
updates:

  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 0
    allow:
      - dependency-type: "direct"
    schedule:
      interval: "daily"
    reviewers:
      - "VKCOM/vk-sec"
      - "VKCOM/statshouse"

  # mandatory check for github actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "VKCOM/vk-sec"
      - "VKCOM/tl"
