version: 2
updates:

  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 0
    allow:
      - dependency-type: "direct"
    schedule:
      interval: "daily"
    reviewers:
      - "VKCOM/vk-sec"
      - "VKCOM/tl"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "VKCOM/vk-sec"
      - "VKCOM/tl"
